version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/
    volumes:
      - .:/var/www/
    ports:
      - "80:80"
    expose:
      - "80"
